version: "3"

services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - net_apimern
    volumes:
      - .:/usr/src/app

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - "27018:27017"
    networks:
      - net_apimern

volumes:
  mongodb:

networks:
  net_apimern: